### ISSUE TITLE
您好，想请教几个问题

### ISSUE THREAD

**Issue by caozheng19** [doliawu/ScoreCrawler#1]
var cookie = res.client._httpMessage.path.toString();
        cookie = cookie.match(/\([a-z,A-Z,0-9]*\)/);
        cookie = cookie[0];
    
可以告诉我这几行代码每行代码进行了什么处理吗？

**Comment by caozheng19** [comment]
还有 验证码是不是一直都是用的空啊  现在是不是修复这个bug了

**Comment by doliawu** [comment]
1. 用正则表达式把URL里的cookie拿出来
2. 是的，已经修复了
